# Generated by Django 5.0 on 2024-09-14 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_bank_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bank',
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('account_no', models.CharField(max_length=150, unique=True, verbose_name='Account No.')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('bank_branch', models.CharField(max_length=100, verbose_name='Bank Branch')),
                ('total', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=15, null=True, verbose_name='Account Balance')),
                ('is_client', models.BooleanField(blank=True, default=False, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='configurations.bank', verbose_name='Bank Name')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_bank_account_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bank_account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Branch')),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_branches_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'branches',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='ClientUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Client Name')),
                ('name_id', models.IntegerField(blank=True, null=True, verbose_name='client code')),
                ('role', models.IntegerField(blank=True, choices=[(0, '--Select Account Type--'), (1, 'Client'), (2, 'Employee'), (3, 'Vendor')], default=0, null=True)),
                ('is_client', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('is_vendor', models.BooleanField(default=False)),
                ('mobile', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Mobile')),
                ('balance', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15, null=True, verbose_name='User Balance')),
                ('credit', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15, null=True, verbose_name='Amount The User Have')),
                ('debit', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15, null=True, verbose_name='Amount To Be Catched From The User')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_client_users_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client_users',
                'verbose_name_plural': 'Client Users',
            },
        ),
        migrations.CreateModel(
            name='ClinicName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Clinic Name')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_clinic_name_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clinic_names',
                'verbose_name_plural': 'Clinic Name',
            },
        ),
        migrations.CreateModel(
            name='CreateClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_clinic_name', to='configurations.clinicname', verbose_name='Clinic Name')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_clinic_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'doctor_names',
                'verbose_name_plural': 'Doctor Names',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_make_departments_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'departments',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='DoctorNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Doctor Name')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_doctornames_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'doctor_names',
                'verbose_name_plural': 'Doctor Names',
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Doctor Specialization')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_name_specializations', to='configurations.doctornames')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_doctor_specialization_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'doctor_specialization',
                'verbose_name_plural': 'Doctor Specializations',
            },
        ),
        migrations.AddField(
            model_name='clinicname',
            name='doctor_specialization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specializations_clinic', to='configurations.doctorspecializations'),
        ),
        migrations.CreateModel(
            name='PosStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Text', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='Text', null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_branch', to='configurations.branches', verbose_name='Branch')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_pos_station_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pos_station',
                'verbose_name_plural': 'PosStations',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnitNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_unit_names_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'unit_names',
                'verbose_name_plural': 'UnitNames',
            },
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['name'], name='configurati_name_a48d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['code'], name='configurati_code_fec6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['active'], name='configurati_active_508ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['created_at'], name='configurati_created_2258a5_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['updated_at'], name='configurati_updated_276c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['is_deleted'], name='configurati_is_dele_42d547_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['deleted_at'], name='configurati_deleted_4e4e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_no'], name='configurati_account_761471_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['bank_branch'], name='configurati_bank_br_6b74f3_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['code'], name='configurati_code_52ad99_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_client'], name='configurati_is_clie_eddd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['active'], name='configurati_active_7622c9_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['created_at'], name='configurati_created_2fc51e_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['updated_at'], name='configurati_updated_55b9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_deleted'], name='configurati_is_dele_255533_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['deleted_at'], name='configurati_deleted_aa58e9_idx'),
        ),
        migrations.AddIndex(
            model_name='branches',
            index=models.Index(fields=['name'], name='configurati_name_7b9414_idx'),
        ),
        migrations.AddIndex(
            model_name='branches',
            index=models.Index(fields=['code'], name='configurati_code_3e5b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='branches',
            index=models.Index(fields=['active'], name='configurati_active_55c99e_idx'),
        ),
        migrations.AddIndex(
            model_name='branches',
            index=models.Index(fields=['created_at'], name='configurati_created_91614d_idx'),
        ),
        migrations.AddIndex(
            model_name='branches',
            index=models.Index(fields=['updated_at'], name='configurati_updated_ae5ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='branches',
            index=models.Index(fields=['is_deleted'], name='configurati_is_dele_de1627_idx'),
        ),
        migrations.AddIndex(
            model_name='branches',
            index=models.Index(fields=['deleted_at'], name='configurati_deleted_8c041c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientusers',
            index=models.Index(fields=['name'], name='configurati_name_851fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='clientusers',
            index=models.Index(fields=['name_id'], name='configurati_name_id_9a5796_idx'),
        ),
        migrations.AddIndex(
            model_name='clientusers',
            index=models.Index(fields=['role'], name='configurati_role_e52f75_idx'),
        ),
        migrations.AddIndex(
            model_name='clientusers',
            index=models.Index(fields=['balance'], name='configurati_balance_bc65aa_idx'),
        ),
        migrations.AddIndex(
            model_name='clientusers',
            index=models.Index(fields=['active'], name='configurati_active_cb93d2_idx'),
        ),
        migrations.AddIndex(
            model_name='clientusers',
            index=models.Index(fields=['created_at'], name='configurati_created_a11701_idx'),
        ),
        migrations.AddIndex(
            model_name='clientusers',
            index=models.Index(fields=['updated_at'], name='configurati_updated_4ee3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='clientusers',
            index=models.Index(fields=['is_deleted'], name='configurati_is_dele_b993fb_idx'),
        ),
        migrations.AddIndex(
            model_name='clientusers',
            index=models.Index(fields=['deleted_at'], name='configurati_deleted_ace5af_idx'),
        ),
        migrations.AddIndex(
            model_name='createclinic',
            index=models.Index(fields=['name'], name='configurati_name_id_70f6df_idx'),
        ),
        migrations.AddIndex(
            model_name='createclinic',
            index=models.Index(fields=['code'], name='configurati_code_dcccac_idx'),
        ),
        migrations.AddIndex(
            model_name='createclinic',
            index=models.Index(fields=['active'], name='configurati_active_a26f46_idx'),
        ),
        migrations.AddIndex(
            model_name='createclinic',
            index=models.Index(fields=['created_at'], name='configurati_created_2c01cc_idx'),
        ),
        migrations.AddIndex(
            model_name='createclinic',
            index=models.Index(fields=['updated_at'], name='configurati_updated_cdff70_idx'),
        ),
        migrations.AddIndex(
            model_name='createclinic',
            index=models.Index(fields=['is_deleted'], name='configurati_is_dele_78bbd1_idx'),
        ),
        migrations.AddIndex(
            model_name='createclinic',
            index=models.Index(fields=['deleted_at'], name='configurati_deleted_14190d_idx'),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['name'], name='configurati_name_755ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['active'], name='configurati_active_746fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['created_at'], name='configurati_created_36a71f_idx'),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['updated_at'], name='configurati_updated_868988_idx'),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['is_deleted'], name='configurati_is_dele_1a9841_idx'),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['deleted_at'], name='configurati_deleted_2ba365_idx'),
        ),
        migrations.AddIndex(
            model_name='doctornames',
            index=models.Index(fields=['name'], name='configurati_name_291e29_idx'),
        ),
        migrations.AddIndex(
            model_name='doctornames',
            index=models.Index(fields=['code'], name='configurati_code_0fc536_idx'),
        ),
        migrations.AddIndex(
            model_name='doctornames',
            index=models.Index(fields=['active'], name='configurati_active_1aa79e_idx'),
        ),
        migrations.AddIndex(
            model_name='doctornames',
            index=models.Index(fields=['created_at'], name='configurati_created_02b811_idx'),
        ),
        migrations.AddIndex(
            model_name='doctornames',
            index=models.Index(fields=['updated_at'], name='configurati_updated_f4dcc0_idx'),
        ),
        migrations.AddIndex(
            model_name='doctornames',
            index=models.Index(fields=['is_deleted'], name='configurati_is_dele_33e393_idx'),
        ),
        migrations.AddIndex(
            model_name='doctornames',
            index=models.Index(fields=['deleted_at'], name='configurati_deleted_d17c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorspecializations',
            index=models.Index(fields=['name'], name='configurati_name_f4176a_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorspecializations',
            index=models.Index(fields=['code'], name='configurati_code_a15614_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorspecializations',
            index=models.Index(fields=['active'], name='configurati_active_75fd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorspecializations',
            index=models.Index(fields=['created_at'], name='configurati_created_493dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorspecializations',
            index=models.Index(fields=['updated_at'], name='configurati_updated_570074_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorspecializations',
            index=models.Index(fields=['is_deleted'], name='configurati_is_dele_a8815a_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorspecializations',
            index=models.Index(fields=['deleted_at'], name='configurati_deleted_54c1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicname',
            index=models.Index(fields=['name'], name='configurati_name_b343db_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicname',
            index=models.Index(fields=['code'], name='configurati_code_812963_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicname',
            index=models.Index(fields=['active'], name='configurati_active_281171_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicname',
            index=models.Index(fields=['created_at'], name='configurati_created_37fbea_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicname',
            index=models.Index(fields=['updated_at'], name='configurati_updated_628dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicname',
            index=models.Index(fields=['is_deleted'], name='configurati_is_dele_966d62_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicname',
            index=models.Index(fields=['deleted_at'], name='configurati_deleted_790a61_idx'),
        ),
        migrations.AddIndex(
            model_name='posstation',
            index=models.Index(fields=['name'], name='configurati_name_0c3132_idx'),
        ),
        migrations.AddIndex(
            model_name='posstation',
            index=models.Index(fields=['code'], name='configurati_code_5bfe6d_idx'),
        ),
        migrations.AddIndex(
            model_name='posstation',
            index=models.Index(fields=['active'], name='configurati_active_12ce99_idx'),
        ),
        migrations.AddIndex(
            model_name='posstation',
            index=models.Index(fields=['created_at'], name='configurati_created_dc03a1_idx'),
        ),
        migrations.AddIndex(
            model_name='posstation',
            index=models.Index(fields=['updated_at'], name='configurati_updated_5bbc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='posstation',
            index=models.Index(fields=['is_deleted'], name='configurati_is_dele_aa3dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='posstation',
            index=models.Index(fields=['deleted_at'], name='configurati_deleted_8890cd_idx'),
        ),
        migrations.AddIndex(
            model_name='unitnames',
            index=models.Index(fields=['name'], name='configurati_name_a40834_idx'),
        ),
        migrations.AddIndex(
            model_name='unitnames',
            index=models.Index(fields=['code'], name='configurati_code_2f34aa_idx'),
        ),
        migrations.AddIndex(
            model_name='unitnames',
            index=models.Index(fields=['active'], name='configurati_active_8e0f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='unitnames',
            index=models.Index(fields=['created_at'], name='configurati_created_426fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='unitnames',
            index=models.Index(fields=['updated_at'], name='configurati_updated_de93a4_idx'),
        ),
        migrations.AddIndex(
            model_name='unitnames',
            index=models.Index(fields=['is_deleted'], name='configurati_is_dele_259711_idx'),
        ),
        migrations.AddIndex(
            model_name='unitnames',
            index=models.Index(fields=['deleted_at'], name='configurati_deleted_cb514d_idx'),
        ),
    ]
