# Generated by Django 5.0 on 2024-07-20 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('age', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, max_length=150, null=True)),
                ('cardid', models.CharField(blank=True, max_length=20, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('barurl', models.CharField(blank=True, max_length=200, null=True)),
                ('barimg', models.ImageField(blank=True, null=True, upload_to='patients')),
            ],
        ),
    ]
