# Generated by Django 5.0 on 2024-08-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdata', '0003_alter_patients_options_alter_patients_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
