# Generated by Django 5.0 on 2024-07-26 12:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientdata', '0002_alter_patients_mobile_alter_patients_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasthist', models.CharField(blank=True, max_length=150, null=True)),
                ('histdate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('remarknote', models.CharField(blank=True, max_length=1000, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.patients')),
            ],
        ),
    ]
