# Generated by Django 4.2.5 on 2023-11-11 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreateVisa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                ("deleted_at", models.DateTimeField(auto_now=True)),
                (
                    "visa_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Visa Owner Name",
                    ),
                ),
                (
                    "expire_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Expire Date"
                    ),
                ),
                (
                    "visa_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Visa Number",
                    ),
                ),
                (
                    "bank_branch",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Bank Branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "create_visa",
                "verbose_name_plural": "Create Visa",
            },
        ),
        migrations.CreateModel(
            name="CreateWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                ("deleted_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Wallet Name"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        default="", max_length=30, verbose_name="Mobile Number"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        default="", max_length=120, verbose_name="Account Name / Email"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Wallet Amount",
                    ),
                ),
            ],
            options={
                "verbose_name": "create_wallet",
                "verbose_name_plural": "Create Wallets",
            },
        ),
    ]
