# Generated by Django 5.0 on 2024-10-14 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0002_remove_doctorspecializations_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='wallet')),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_wallet_names_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet_name',
                'verbose_name_plural': 'Wallet Names',
            },
        ),
        migrations.CreateModel(
            name='CreateWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('name', models.IntegerField(choices=[(0, '--Select Wallet Name--'), (1, 'Vodafone'), (2, 'Etisalate'), (3, 'We'), (4, 'Pay Mob'), (5, 'Insta Pay'), (6, 'Orange')], default=0, verbose_name='Wallet Name')),
                ('wallet_type', models.IntegerField(blank=True, choices=[(0, '--Select Wallet Type--'), (1, 'Mobile'), (2, 'Account Name')], default=0, null=True, verbose_name='Wallet Type')),
                ('mobile', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Mobile Number')),
                ('account_name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Account Name / Email')),
                ('total', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15, null=True, verbose_name='Wallet Amount')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('is_client', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_create_wallet_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_name', to='management.walletname', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'create_wallet',
                'verbose_name_plural': 'Create Wallets',
            },
        ),
        migrations.CreateModel(
            name='CreateVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('visa_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Visa Owner Name')),
                ('expire_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Expire Date')),
                ('visa_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Visa Number')),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Branch')),
                ('total', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15, null=True, verbose_name='Visa Balance')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code')),
                ('is_client', models.BooleanField(blank=True, default=False, null=True)),
                ('account_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.bankaccount', verbose_name='Bank Account')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_name', to='configurations.bank', verbose_name='Bank Name')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_create_visa_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'create_visa',
                'verbose_name_plural': 'Create Visa',
                'indexes': [models.Index(fields=['visa_name'], name='management__visa_na_7b7881_idx'), models.Index(fields=['expire_date'], name='management__expire__7b171f_idx'), models.Index(fields=['visa_no'], name='management__visa_no_1f1276_idx'), models.Index(fields=['active'], name='management__active_18cbed_idx'), models.Index(fields=['is_client'], name='management__is_clie_4c1b76_idx'), models.Index(fields=['created_at'], name='management__created_35b98d_idx'), models.Index(fields=['updated_at'], name='management__updated_66c2cc_idx'), models.Index(fields=['is_deleted'], name='management__is_dele_57ab5b_idx'), models.Index(fields=['deleted_at'], name='management__deleted_506c77_idx'), models.Index(fields=['code'], name='management__code_61106e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='walletname',
            index=models.Index(fields=['name'], name='management__name_c2a38a_idx'),
        ),
        migrations.AddIndex(
            model_name='walletname',
            index=models.Index(fields=['code'], name='management__code_d1a594_idx'),
        ),
        migrations.AddIndex(
            model_name='walletname',
            index=models.Index(fields=['active'], name='management__active_1e1d16_idx'),
        ),
        migrations.AddIndex(
            model_name='walletname',
            index=models.Index(fields=['created_at'], name='management__created_bab1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='walletname',
            index=models.Index(fields=['updated_at'], name='management__updated_f678ef_idx'),
        ),
        migrations.AddIndex(
            model_name='walletname',
            index=models.Index(fields=['is_deleted'], name='management__is_dele_48bb12_idx'),
        ),
        migrations.AddIndex(
            model_name='walletname',
            index=models.Index(fields=['deleted_at'], name='management__deleted_5a9f22_idx'),
        ),
        migrations.AddIndex(
            model_name='createwallet',
            index=models.Index(fields=['name'], name='management__name_df6ace_idx'),
        ),
        migrations.AddIndex(
            model_name='createwallet',
            index=models.Index(fields=['mobile'], name='management__mobile_cae6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='createwallet',
            index=models.Index(fields=['account_name'], name='management__account_e74bec_idx'),
        ),
        migrations.AddIndex(
            model_name='createwallet',
            index=models.Index(fields=['code'], name='management__code_b62645_idx'),
        ),
        migrations.AddIndex(
            model_name='createwallet',
            index=models.Index(fields=['is_client'], name='management__is_clie_4f9b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='createwallet',
            index=models.Index(fields=['active'], name='management__active_8f71c6_idx'),
        ),
        migrations.AddIndex(
            model_name='createwallet',
            index=models.Index(fields=['created_at'], name='management__created_95306b_idx'),
        ),
        migrations.AddIndex(
            model_name='createwallet',
            index=models.Index(fields=['updated_at'], name='management__updated_839eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='createwallet',
            index=models.Index(fields=['is_deleted'], name='management__is_dele_d010d4_idx'),
        ),
        migrations.AddIndex(
            model_name='createwallet',
            index=models.Index(fields=['deleted_at'], name='management__deleted_f9fb41_idx'),
        ),
    ]
