# Generated by Django 4.2.5 on 2023-11-11 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("management", "0001_initial"),
        ("configurations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="createwallet",
            name="updated_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_make_create_wallet_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="createwallet",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="createvisa",
            name="account_no",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configurations.bankaccount",
                verbose_name="Bank Account",
            ),
        ),
        migrations.AddField(
            model_name="createvisa",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_name",
                to="configurations.bank",
                verbose_name="Bank Name",
            ),
        ),
        migrations.AddField(
            model_name="createvisa",
            name="updated_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_make_create_visa_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="createvisa",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="createwallet",
            index=models.Index(fields=["name"], name="management__name_df6ace_idx"),
        ),
        migrations.AddIndex(
            model_name="createwallet",
            index=models.Index(fields=["mobile"], name="management__mobile_cae6ee_idx"),
        ),
        migrations.AddIndex(
            model_name="createwallet",
            index=models.Index(
                fields=["account_name"], name="management__account_e74bec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="createwallet",
            index=models.Index(fields=["active"], name="management__active_8f71c6_idx"),
        ),
        migrations.AddIndex(
            model_name="createwallet",
            index=models.Index(
                fields=["created_at"], name="management__created_95306b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="createwallet",
            index=models.Index(
                fields=["updated_at"], name="management__updated_839eb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="createwallet",
            index=models.Index(
                fields=["is_deleted"], name="management__is_dele_d010d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="createwallet",
            index=models.Index(
                fields=["deleted_at"], name="management__deleted_f9fb41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="createvisa",
            index=models.Index(
                fields=["visa_name"], name="management__visa_na_7b7881_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="createvisa",
            index=models.Index(
                fields=["expire_date"], name="management__expire__7b171f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="createvisa",
            index=models.Index(
                fields=["visa_no"], name="management__visa_no_1f1276_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="createvisa",
            index=models.Index(fields=["active"], name="management__active_18cbed_idx"),
        ),
        migrations.AddIndex(
            model_name="createvisa",
            index=models.Index(
                fields=["created_at"], name="management__created_35b98d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="createvisa",
            index=models.Index(
                fields=["updated_at"], name="management__updated_66c2cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="createvisa",
            index=models.Index(
                fields=["is_deleted"], name="management__is_dele_57ab5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="createvisa",
            index=models.Index(
                fields=["deleted_at"], name="management__deleted_506c77_idx"
            ),
        ),
    ]
