# Generated by Django 4.2.5 on 2023-12-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0004_remove_bankaccount_total_and_more"),
        ("management", "0003_remove_createwallet_balance_createvisa_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="createvisa",
            name="total",
        ),
        migrations.RemoveField(
            model_name="createwallet",
            name="total",
        ),
        migrations.AddField(
            model_name="createwallet",
            name="balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Wallet Amount",
            ),
        ),
        migrations.AlterField(
            model_name="createvisa",
            name="account_no",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="configurations.bankaccount",
                verbose_name="Bank Account",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="createvisa",
            name="bank",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_name",
                to="configurations.bank",
                verbose_name="Bank Name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="createvisa",
            name="visa_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Visa Owner Name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="createvisa",
            name="visa_no",
            field=models.CharField(
                default="v", max_length=100, unique=True, verbose_name="Visa Number"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="createwallet",
            name="account_name",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="Account Name / Email",
            ),
        ),
        migrations.AlterField(
            model_name="createwallet",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Mobile Number"
            ),
        ),
        migrations.AlterField(
            model_name="createwallet",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Wallet Name"),
        ),
    ]
