# Generated by Django 4.2.5 on 2023-12-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0005_bankaccount_total_clientusers_is_client_and_more"),
        (
            "management",
            "0004_remove_createvisa_total_remove_createwallet_total_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="createwallet",
            name="balance",
        ),
        migrations.AddField(
            model_name="createvisa",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=0.0,
                max_digits=15,
                null=True,
                verbose_name="Visa Balance",
            ),
        ),
        migrations.AddField(
            model_name="createwallet",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=0.0,
                max_digits=15,
                null=True,
                verbose_name="Wallet Amount",
            ),
        ),
        migrations.AlterField(
            model_name="createvisa",
            name="account_no",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configurations.bankaccount",
                verbose_name="Bank Account",
            ),
        ),
        migrations.AlterField(
            model_name="createvisa",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_name",
                to="configurations.bank",
                verbose_name="Bank Name",
            ),
        ),
        migrations.AlterField(
            model_name="createvisa",
            name="visa_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Visa Owner Name"
            ),
        ),
        migrations.AlterField(
            model_name="createvisa",
            name="visa_no",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Visa Number",
            ),
        ),
        migrations.AlterField(
            model_name="createwallet",
            name="account_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                null=True,
                verbose_name="Account Name / Email",
            ),
        ),
        migrations.AlterField(
            model_name="createwallet",
            name="mobile",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
                null=True,
                verbose_name="Mobile Number",
            ),
        ),
        migrations.AlterField(
            model_name="createwallet",
            name="name",
            field=models.IntegerField(
                choices=[
                    (0, "--Select Wallet Name--"),
                    (1, "Vodafone"),
                    (2, "Etisalate"),
                    (3, "We"),
                    (4, "Pay Mob"),
                    (5, "Insta Pay"),
                    (6, "Orange"),
                ],
                default=0,
                verbose_name="Wallet Name",
            ),
        ),
    ]
