# Generated by Django 4.2.5 on 2024-01-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0006_alter_createvisa_total_alter_createwallet_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="createvisa",
            name="code",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Code"
            ),
        ),
        migrations.AddField(
            model_name="createwallet",
            name="code",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Code"
            ),
        ),
        migrations.AddIndex(
            model_name="createvisa",
            index=models.Index(fields=["code"], name="management__code_61106e_idx"),
        ),
        migrations.AddIndex(
            model_name="createwallet",
            index=models.Index(fields=["code"], name="management__code_b62645_idx"),
        ),
    ]
