# Generated by Django 4.2.5 on 2024-02-29 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("management", "0007_createvisa_code_createwallet_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                ("deleted_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="wallet"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Code"
                    ),
                ),
                (
                    "updated_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_make_wallet_names_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet_name",
                "verbose_name_plural": "Wallet Names",
                "indexes": [
                    models.Index(fields=["name"], name="management__name_c2a38a_idx"),
                    models.Index(fields=["code"], name="management__code_d1a594_idx"),
                    models.Index(
                        fields=["active"], name="management__active_1e1d16_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="management__created_bab1d2_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="management__updated_f678ef_idx"
                    ),
                    models.Index(
                        fields=["is_deleted"], name="management__is_dele_48bb12_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="management__deleted_5a9f22_idx"
                    ),
                ],
            },
        ),
    ]
