# Generated by Django 4.2.5 on 2024-03-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0008_walletname"),
    ]

    operations = [
        migrations.AddField(
            model_name="createwallet",
            name="wallet_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_name",
                to="management.walletname",
                verbose_name="Wallet",
            ),
        ),
        migrations.AddField(
            model_name="createwallet",
            name="wallet_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "--Select Wallet Type--"),
                    (1, "Mobile"),
                    (2, "Account Name"),
                ],
                default=0,
                null=True,
                verbose_name="Wallet Type",
            ),
        ),
    ]
